export const colorRubberBaseKodi = [
  {
    id: "milky7",
    titleKey: "basicCollection.milky7.name",
    price: 163,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "ultraWhite7",
    titleKey: "basicCollection.ultraWhite7.name",
    price: 163,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "milky8",
    titleKey: "basicCollection.milky8.name",
    price: 185,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "watermelon7",
    titleKey: "basicCollection.watermelon7.name",
    price: 160,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "ultimateGray7",
    titleKey: "basicCollection.ultimateGray7.name",
    price: 160,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "illuminating7",
    titleKey: "basicCollection.illuminating7.name",
    price: 160,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "watermelon8",
    titleKey: "basicCollection.watermelon8.name",
    price: 175,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "ultimateGray8",
    titleKey: "basicCollection.ultimateGray8.name",
    price: 175,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "illuminating8",
    titleKey: "basicCollection.illuminating8.name",
    price: 175,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "black7",
    titleKey: "basicCollection.black7.name",
    price: 163,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "black8",
    titleKey: "basicCollection.black8.name",
    price: 185,
    image: "/placeholder_image.webp",
    href: "#",
  },
];

export default colorRubberBaseKodi;
