export const kodi = [
  { id: "gel-polish", nameKey: "gelPolish", route: "/kodi/collections" },
  { id: "bases-tops", nameKey: "basesTops", route: "/kodi/kodiBases" },
  { id: "gel-paints", nameKey: "gelPaints", route: "#" },
  { id: "nail-polish", nameKey: "nailPolish", route: "#" },
  { id: "poly-gel", nameKey: "polyGel", route: "#" },
  { id: "builder-gels", nameKey: "builderGels", route: "#" },
  { id: "forms-tips", nameKey: "formsTips", route: "#" },
  { id: "acrylic-system", nameKey: "acrylicSystem", route: "#" },
  { id: "monomers", nameKey: "monomers", route: "#" },
  { id: "special-products", nameKey: "specialProducts", route: "#" },
  { id: "tools", nameKey: "tools", route: "#" },
  { id: "files-buffers", nameKey: "filesBuffers", route: "#" },
  { id: "brushes-dots", nameKey: "brushesDots", route: "#" },
  { id: "accessories", nameKey: "accessories", route: "#" },
  { id: "design", nameKey: "design", route: "#" },
  { id: "lamps-collectors", nameKey: "lampsCollectors", route: "#" },
  { id: "drills", nameKey: "drills", route: "#" },
  { id: "home-kits", nameKey: "homeKits", route: "#" },
  { id: "palettes", nameKey: "palettes", route: "#" },
];
export default kodi;
