const crystalDropsKodi = [
  {
    id: "crystalDrops01",
    titleKey: "crystalDrops.crystalDrops01.name",
    collection: "Crystal Drops",
    color: "white",
    volume: 7,
    article: "CD-001",
    price: 175,
    sale: false,
    isNew: false,
    inStock: true,
    image:
      "/images/kodi/kodi_base_image/kodi_colored_base_collections/crystal_drops_base_kodi/crystal_drops_01.png",
    href: "#",
  },
  {
    id: "crystalDrops02",
    titleKey: "crystalDrops.crystalDrops02.name",
    collection: "Crystal Drops",
    color: "milk",
    volume: 7,
    article: "CD-002",
    price: 175,
    sale: false,
    isNew: true,
    inStock: true,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "crystalDrops03",
    titleKey: "crystalDrops.crystalDrops03.name",
    collection: "Crystal Drops",
    color: "pink",
    volume: 7,
    article: "CD-003",
    price: 175,
    sale: false,
    isNew: true,
    inStock: true,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "crystalDrops04",
    titleKey: "crystalDrops.crystalDrops04.name",
    collection: "Crystal Drops",
    color: "nude",
    volume: 7,
    article: "CD-004",
    price: 175,
    sale: false,
    isNew: true,
    inStock: true,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "crystalDrops05",
    titleKey: "crystalDrops.crystalDrops05.name",
    collection: "Crystal Drops",
    color: "beige",
    volume: 7,
    article: "CD-005",
    price: 175,
    sale: false,
    isNew: true,
    inStock: true,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "crystalDrops06",
    titleKey: "crystalDrops.crystalDrops06.name",
    collection: "Crystal Drops",
    color: "peach",
    volume: 7,
    article: "CD-006",
    price: 175,
    sale: false,
    isNew: true,
    inStock: true,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "crystalDrops07",
    titleKey: "crystalDrops.crystalDrops07.name",
    collection: "Crystal Drops",
    color: "red",
    volume: 7,
    article: "CD-007",
    price: 175,
    sale: false,
    isNew: true,
    inStock: true,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "crystalDrops08",
    titleKey: "crystalDrops.crystalDrops08.name",
    collection: "Crystal Drops",
    color: "orange",
    volume: 7,
    article: "CD-008",
    price: 175,
    sale: false,
    isNew: true,
    inStock: true,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "crystalDrops09",
    titleKey: "crystalDrops.crystalDrops09.name",
    collection: "Crystal Drops",
    color: "yellow",
    volume: 7,
    article: "CD-009",
    price: 175,
    sale: false,
    isNew: true,
    inStock: true,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "crystalDrops10",
    titleKey: "crystalDrops.crystalDrops10.name",
    collection: "Crystal Drops",
    color: "green",
    volume: 7,
    article: "CD-010",
    price: 175,
    sale: false,
    isNew: true,
    inStock: true,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "crystalDrops11",
    titleKey: "crystalDrops.crystalDrops11.name",
    collection: "Crystal Drops",
    color: "blue",
    volume: 7,
    article: "CD-011",
    price: 175,
    sale: false,
    isNew: true,
    inStock: true,
    image: "/placeholder_image.webp",
    href: "#",
  },
  {
    id: "crystalDrops12",
    titleKey: "crystalDrops.crystalDrops12.name",
    collection: "Crystal Drops",
    color: "black",
    volume: 7,
    article: "CD-012",
    price: 175,
    sale: false,
    isNew: true,
    inStock: true,
    image: "/placeholder_image.webp",
    href: "#",
  },
];

export default crystalDropsKodi;
