export const camouflageBasesKodi = [
  {
    id: "12696",
    title: "Камуфлююче базове покриття Cover Base Pro",
    subtitle: "Камуфлююче базове покриття Cover Base Pro №10, 7 мл",
    oldPrice: null,
    newPrice: 185,
    volume: "7 мл",
    image: "",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_788&product_id=12696",
  },
  {
    id: "12695",
    title: "Камуфлююче базове покриття Cover Base Pro",
    subtitle: "Камуфлююче базове покриття Cover Base Pro №09, 7 мл",
    oldPrice: null,
    newPrice: 185,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Pro/Cover%20Base%20Pro_09-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_788&product_id=12695",
  },
  {
    id: "12694",
    title: "Камуфлююче базове покриття Cover Base Pro",
    subtitle: "Камуфлююче базове покриття Cover Base Pro №08, 7 мл",
    oldPrice: null,
    newPrice: 185,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Pro/Cover%20Base%20Pro_08-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_788&product_id=12694",
  },
  {
    id: "12693",
    title: "Камуфлююче базове покриття Cover Base Pro",
    subtitle: "Камуфлююче базове покриття Cover Base Pro №07, 7 мл",
    oldPrice: null,
    newPrice: 185,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Pro/Cover%20Base%20Pro_07-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_788&product_id=12693",
  },
  {
    id: "12692",
    title: "Камуфлююче базове покриття Cover Base Pro",
    subtitle: "Камуфлююче базове покриття Cover Base Pro №06, 7 мл",
    oldPrice: null,
    newPrice: 185,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Pro/Cover%20Base%20Pro_06-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_788&product_id=12692",
  },
  {
    id: "12691",
    title: "Камуфлююче базове покриття Cover Base Pro",
    subtitle: "Камуфлююче базове покриття Cover Base Pro №05, 7 мл",
    oldPrice: null,
    newPrice: 185,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Pro/Cover%20Base%20Pro_05-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_788&product_id=12691",
  },
  {
    id: "12690",
    title: "Камуфлююче базове покриття Cover Base Pro",
    subtitle: "Камуфлююче базове покриття Cover Base Pro №04, 7 мл",
    oldPrice: null,
    newPrice: 185,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Pro/Cover%20Base%20Pro_04-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_788&product_id=12690",
  },
  {
    id: "12689",
    title: "Камуфлююче базове покриття Cover Base Pro",
    subtitle: "Камуфлююче базове покриття Cover Base Pro №03, 7 мл",
    oldPrice: null,
    newPrice: 185,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Pro/Cover%20Base%20Pro_03-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_788&product_id=12689",
  },
  {
    id: "12688",
    title: "Камуфлююче базове покриття Cover Base Pro",
    subtitle: "Камуфлююче базове покриття Cover Base Pro №02, 7 мл",
    oldPrice: null,
    newPrice: 185,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Pro/Cover%20Base%20Pro_02-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_788&product_id=12688",
  },
  {
    id: "12687",
    title: "Камуфлююче базове покриття Cover Base Pro",
    subtitle: "Камуфлююче базове покриття Cover Base Pro №01, 7 мл",
    oldPrice: null,
    newPrice: 185,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Pro/Cover%20Base%20Pro_01-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_788&product_id=12687",
  },
  {
    id: "12668",
    title: "Камуфлююче базове покриття Cover base",
    subtitle:
      "Камуфлююче базове покриття з тонким носиком Cover Base Gel 14, 30 мл",
    oldPrice: 500,
    newPrice: 350,
    volume: "30 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20base%20gel/500x600_30ml-cover14-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12668",
  },
  {
    id: "12667",
    title: "Камуфлююче базове покриття Cover base",
    subtitle:
      "Камуфлююче базове покриття з тонким носиком Cover Base Gel 13, 30 мл",
    oldPrice: 500,
    newPrice: 350,
    volume: "30 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20base%20gel/500x600_30ml-cover13-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12667",
  },
  {
    id: "12666",
    title: "Камуфлююче базове покриття Cover base",
    subtitle:
      "Камуфлююче базове покриття з тонким носиком Cover Base Gel 12, 30 мл",
    oldPrice: 500,
    newPrice: 350,
    volume: "30 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20base%20gel/500x600_30ml-cover12-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12666",
  },
  {
    id: "12665",
    title: "Камуфлююче базове покриття Cover base",
    subtitle:
      "Камуфлююче базове покриття з тонким носиком Cover Base Gel 11, 30 мл",
    oldPrice: 500,
    newPrice: 350,
    volume: "30 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20base%20gel/500x600_30ml-cover11-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12665",
  },
  {
    id: "12663",
    title: "Камуфлююче базове покриття Cover base",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 19, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Gel%207%20ml/500x600_7ml-cover19-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12663",
  },
  {
    id: "12664",
    title: "Камуфлююче базове покриття Cover base",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 18, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Gel%207%20ml/500x600_7ml-cover18-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12664",
  },
  {
    id: "12662",
    title: "Камуфлююче базове покриття Cover base",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 17, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Gel%207%20ml/500x600_7ml-cover17-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12662",
  },
  {
    id: "12661",
    title: "Камуфлююче базове покриття Cover base",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 16, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Gel%207%20ml/500x600_7ml-cover16-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12661",
  },
  {
    id: "12660",
    title: "Камуфлююче базове покриття Cover base",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 15, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Gel%207%20ml/500x600_7ml-cover15-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12660",
  },
  {
    id: "12659",
    title: "Камуфлююче базове покриття Cover base",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 14, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Gel%207%20ml/500x600_7ml-cover14-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12659",
  },
  {
    id: "12658",
    title: "Камуфлююче базове покриття Cover base",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 13, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Gel%207%20ml/500x600_7ml-cover13-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12658",
  },
  {
    id: "12657",
    title: "Камуфлююче базове покриття Cover base",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 12, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Gel%207%20ml/500x600_7ml-cover12-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12657",
  },
  {
    id: "12656",
    title: "Камуфлююче базове покриття Cover base",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 11, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%20Gel%207%20ml/500x600_7ml-cover11-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12656",
  },
  {
    id: "12566",
    title: "Камуфлююче базове покриття",
    subtitle:
      "Камуфлююче базове покриття з тонким носиком Cover Base Gel 10, 30 мл",
    oldPrice: 500,
    newPrice: 350,
    volume: "30 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20base%20gel/Cover%20Base%2030ml%2010-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12566",
  },
  {
    id: "12565",
    title: "Камуфлююче базове покриття",
    subtitle:
      "Камуфлююче базове покриття з тонким носиком Cover Base Gel 09, 30 мл",
    oldPrice: 500,
    newPrice: 350,
    volume: "30 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20base%20gel/Cover%20Base%2030ml%209-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12565",
  },
  {
    id: "12564",
    title: "Камуфлююче базове покриття",
    subtitle:
      "Камуфлююче базове покриття з тонким носиком Cover Base Gel 08, 30 мл",
    oldPrice: 500,
    newPrice: 350,
    volume: "30 мл",
    image: "",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12564",
  },
  {
    id: "12563",
    title: "Камуфлююче базове покриття",
    subtitle:
      "Камуфлююче базове покриття з тонким носиком Cover Base Gel 07, 30 мл",
    oldPrice: 500,
    newPrice: 350,
    volume: "30 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20base%20gel/Cover%20Base%2030ml%207-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12563",
  },
  {
    id: "12562",
    title: "Камуфлююче базове покриття",
    subtitle:
      "Камуфлююче базове покриття з тонким носиком Cover Base Gel 06, 30 мл",
    oldPrice: 500,
    newPrice: 350,
    volume: "30 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20base%20gel/Cover%20Base%2030ml%206-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12562",
  },
  {
    id: "12561",
    title: "Камуфлююче базове покриття",
    subtitle:
      "Камуфлююче базове покриття з тонким носиком Cover Base Gel 05, 30 мл",
    oldPrice: 500,
    newPrice: 350,
    volume: "30 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20base%20gel/Cover%20Base%2030ml%205-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12561",
  },
  {
    id: "12560",
    title: "Камуфлююче базове покриття",
    subtitle:
      "Камуфлююче базове покриття з тонким носиком Cover Base Gel 04, 30 мл",
    oldPrice: 500,
    newPrice: 350,
    volume: "30 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20base%20gel/Cover%20Base%2030ml%204-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12560",
  },
  {
    id: "12559",
    title: "Камуфлююче базове покриття",
    subtitle:
      "Камуфлююче базове покриття з тонким носиком Cover Base Gel 03, 30 мл",
    oldPrice: 500,
    newPrice: 350,
    volume: "30 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20base%20gel/Cover%20Base%2030ml%203-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12559",
  },
  {
    id: "12558",
    title: "Камуфлююче базове покриття",
    subtitle:
      "Камуфлююче базове покриття з тонким носиком Cover Base Gel 02, 30 мл",
    oldPrice: 500,
    newPrice: 350,
    volume: "30 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20Base%2030ml%202-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12558",
  },
  {
    id: "12557",
    title: "Камуфлююче базове покриття",
    subtitle:
      "Камуфлююче базове покриття з тонким носиком Cover Base Gel 01, 30 мл",
    oldPrice: 500,
    newPrice: 350,
    volume: "30 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/Cover%20base%20gel/Cover%20Base%2030ml%201-306x390.png",
    href: "https://kodi-professional.ua/uk/index.php?route=product/product&path=278_226_441_495&product_id=12557",
  },
  {
    id: "11479",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Natural Rubber Base Tea Rose, 15 мл",
    oldPrice: 284,
    newPrice: 199,
    volume: "15 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Natural%20Rubber%20Base/TeaRose_NaturalRubber_2000x2000-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/natural-rubber-base/natural-rubber-base-tea-rose_-15-ml/",
  },
  {
    id: "11478",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Natural Rubber Base Pink, 15 мл",
    oldPrice: 284,
    newPrice: 199,
    volume: "15 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Natural%20Rubber%20Base/Pink_NaturalRubber_2000x2000-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/natural-rubber-base/natural-rubber-base-pink_-15-ml/",
  },
  {
    id: "11477",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Natural Rubber Base Pink Ice, 15 мл",
    oldPrice: 284,
    newPrice: 199,
    volume: "15 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Natural%20Rubber%20Base/PinkIce_NaturalRubber_2000x2000-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/natural-rubber-base/natural-rubber-base-pink-ice_-15-ml/",
  },
  {
    id: "11476",
    title: "Камуфлююче базове покриття",
    subtitle:
      "Камуфлююче базове покриття Natural Rubber Base Natural Beige, 15 мл",
    oldPrice: 284,
    newPrice: 199,
    volume: "15 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Natural%20Rubber%20Base/NaturalBeige_NaturalRubber_2000x2000-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/natural-rubber-base/natural-rubber-base-natural-beige_-15-ml/",
  },
  {
    id: "11475",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Natural Rubber Base Ivory, 15 мл",
    oldPrice: 284,
    newPrice: 199,
    volume: "15 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Natural%20Rubber%20Base/Ivory_NaturalRubber_2000x2000-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/natural-rubber-base/natural-rubber-base-ivori_-15-ml/",
  },
  {
    id: "11474",
    title: "Камуфлююче базове покриття",
    subtitle:
      "Камуфлююче базове покриття Natural Rubber Base Dark Beige, 15 мл",
    oldPrice: 284,
    newPrice: 199,
    volume: "15 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Natural%20Rubber%20Base/DarkBeige_NaturalRubber_2000x2000-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/natural-rubber-base/natural-rubber-base-dark-beige_-15-ml/",
  },
  {
    id: "11297",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Natural Rubber Base Tea Rose, 7 мл",
    oldPrice: 181,
    newPrice: 127,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Natural%20Rubber%20Base/TeaRose_NaturalRubber_2000x2000-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/natural-rubber-base/natural-rubber-base-tea-rose_-7-ml/",
  },
  {
    id: "11296",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Natural Rubber Base Pink, 7 мл",
    oldPrice: 181,
    newPrice: 127,
    volume: "7 мл",
    rating: 5,
    reviews: 3,
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Natural%20Rubber%20Base/Pink_NaturalRubber_2000x2000-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/natural-rubber-base/natural-rubber-base-pink_-7-ml/",
  },
  {
    id: "11295",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Natural Rubber Base Pink Ice, 7 мл",
    oldPrice: 181,
    newPrice: 127,
    volume: "7 мл",
    rating: 0,
    reviews: 0,
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Natural%20Rubber%20Base/PinkIce_NaturalRubber_2000x2000-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/natural-rubber-base/natural-rubber-base-pink-ice_-7-ml/",
  },
  {
    id: "11294",
    title: "Камуфлююче базове покриття",
    subtitle:
      "Камуфлююче базове покриття Natural Rubber Base Natural Beige, 7 мл",
    oldPrice: 181,
    newPrice: 127,
    volume: "7 мл",
    rating: 0,
    reviews: 0,
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Natural%20Rubber%20Base/NaturalBeige_NaturalRubber_2000x2000-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/natural-rubber-base/natural-rubber-base-natural-beige_-7-ml/",
  },
  {
    id: "11293",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Natural Rubber Base Ivory, 7 мл",
    oldPrice: 181,
    newPrice: 127,
    volume: "7 мл",
    rating: 5,
    reviews: 2,
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Natural%20Rubber%20Base/Ivory_NaturalRubber_2000x2000-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/natural-rubber-base/natural-rubber-base-ivori_-7-ml/",
  },
  {
    id: "11292",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Natural Rubber Base Dark Beige, 7 мл",
    oldPrice: 181,
    newPrice: 127,
    volume: "7 мл",
    rating: 5,
    reviews: 2,
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Natural%20Rubber%20Base/DarkBeige_NaturalRubber_2000x2000-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/natural-rubber-base/natural-rubber-base-dark-beige_-7-ml/",
  },
  {
    id: "10875",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 10, 30 мл",
    oldPrice: 486,
    newPrice: 340,
    volume: "30 мл",
    rating: 5,
    reviews: 2,
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/CoverBase/CoverBase-10-500x600-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-bazove-pokrittya-cover-base-gel-10_-30ml/",
  },
  {
    id: "10874",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 09, 30 мл",
    oldPrice: 486,
    newPrice: 340,
    volume: "30 мл",
    rating: 5,
    reviews: 2,
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/CoverBase/CoverBase-09-500x600-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-bazove-pokrittya-cover-base-gel-09_-30ml/",
  },
  {
    id: "10873",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 08, 30 мл",
    oldPrice: 486,
    newPrice: 340,
    volume: "30 мл",
    rating: 5,
    reviews: 3,
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/CoverBase/CoverBase-08-500x600-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-bazove-pokrittya-cover-base-gel-08_-30ml/",
  },
  {
    id: "10872",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 07, 30 мл",
    oldPrice: 486,
    newPrice: 340,
    volume: "30 мл",
    rating: 5,
    reviews: 2,
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/CoverBase/CoverBase-07-500x600-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-bazove-pokrittya-cover-base-gel-07_-30ml/",
  },
  {
    id: "10871",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 06, 30 мл",
    oldPrice: 486,
    newPrice: 340,
    volume: "30 мл",
    rating: 5,
    reviews: 3,
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/CoverBase/CoverBase-06-500x600-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-bazove-pokrittyya-cover-base-gel-06_-30ml/",
  },
  {
    id: "10870",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 05, 30 мл",
    oldPrice: 486,
    newPrice: 340,
    volume: "30 мл",
    rating: 5,
    reviews: 2,
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/CoverBase/CoverBase-05-500x600-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-bazove-pokrittya-cover-base-gel-05_-30ml/",
  },
  {
    id: "10869",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 04, 30 мл",
    oldPrice: 486,
    newPrice: 340,
    volume: "30 мл",
    rating: 5,
    reviews: 2,
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/CoverBase/CoverBase-04-500x600-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-bazove-pokритtyа-cover-base-gel-04_-30ml/",
  },
  {
    id: "10868",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 03, 30 мл",
    oldPrice: 486,
    newPrice: 340,
    volume: "30 мл",
    rating: 5,
    reviews: 3,
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/CoverBase/CoverBase-03-500x600-306x390.jpg",
    href: "https://kodi-professional.ua/uk/bазa-i-top-dlya-gel-laka/bazatop-для-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-базове-покриття-cover-base-gel-03_-30ml/",
  },
  {
    id: "10867",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 02, 30 мл",
    oldPrice: 486,
    newPrice: 340,
    volume: "30 мл",
    rating: 5,
    reviews: 2,
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/CoverBase/CoverBase-02-500x600-306x390.jpg",
    href: "https://kodi-professional.ua/uk/bазa-i-top-dlya-gel-laka/bazatop-для-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-базове-покриття-cover-base-gel-02_-30ml/",
  },
  {
    id: "10865",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 01, 30 мл",
    oldPrice: 486,
    newPrice: 340,
    volume: "30 мл",
    rating: 5,
    reviews: 3,
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/CoverBase/CoverBase-01-500x600-306x390.jpg",
    href: "https://kodi-professional.ua/uk/bазa-i-top-dlya-gel-laka/bazatop-для-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-базове-покриття-cover-base-gel-01_-30ml/",
  },
  {
    id: "10301",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 10, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image: "",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-bazove-pokrittya-cover-base-gel-10_-7ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "10300",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 09, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Color_base/7%20ml/09_CB-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-bazove-pokrittya-cover-base-gel-09_-7ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "10293",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Shine Milk, 15 мл",
    oldPrice: 288,
    newPrice: 202,
    volume: "15 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/2023/SHINEMILK_15ml-500x600-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-shine-milk_-15ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "10292",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Peach, 15 мл",
    oldPrice: 288,
    newPrice: 202,
    volume: "15 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/2023/PEACH_15ml-500x600-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-peach_-15ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "10291",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Latte, 15 мл",
    oldPrice: 288,
    newPrice: 202,
    volume: "15 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/2023/LATTE_15ml-500x600-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-latte_-15ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "10290",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Delicate Rose, 15 мл",
    oldPrice: 288,
    newPrice: 202,
    volume: "15 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/camuflage%20gel/Lint%20Base/New%20color_500x600_Lint_Base_Delicate_Rose_15_ml-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-delicate-rose_-15ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "10289",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Cold Rose, 15 мл",
    oldPrice: 288,
    newPrice: 202,
    volume: "15 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/2023/COLDROSE_15ml-500x600-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-cold-rose_-15ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9805",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 08, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Color_base/7%20ml/08_CB-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-bazove-pokrittya-cover-base-gel-08_-7ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9804",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 07, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Color_base/7%20ml/07_CB-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-bazove-pokrittya-cover-base-gel-07_-7ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9803",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 06, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Color_base/7%20ml/06_CB-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-bazove-pokrittya-cover-base-gel-06_-7ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9802",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 05, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Color_base/7%20ml/05_CB-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche-bazove-pokrittya-cover-base-gel-05_-7ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9710",
    title: "Камуфлююче базове покриття Lint Base",
    subtitle: "Палітра базового покриття Lint Base (5 тіпс)",
    oldPrice: null,
    newPrice: 25,
    volume: "",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/новый/палитры/lint%20base-306x390.JPG",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/palitra-bazovogo-pokrittya-lint-base-5-tips/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9708",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Shine Milk, 7 мл",
    oldPrice: 159,
    newPrice: 111,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Lint_base/SHINE_MILK_(01)-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-shine-milk_-7ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9707",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Shine Milk, 35 мл",
    oldPrice: 460,
    newPrice: 322,
    volume: "35 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/2023/SHINEMILK_35ml-500x600-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-shine-milk_-35ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9706",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Shine Milk, 12 мл",
    oldPrice: 249,
    newPrice: 174,
    volume: "12 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/2023/SHINEMILK_12ml-500x600-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-shine-milk_-12ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9705",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Peach, 7 мл",
    oldPrice: 159,
    newPrice: 111,
    volume: "7 мл",
    image: "",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-peach_-7ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9704",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Peach, 35 мл",
    oldPrice: 460,
    newPrice: 322,
    volume: "35 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/2023/PEACH_35ml-500x600-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-peach_-35ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9703",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Peach, 12 мл",
    oldPrice: 249,
    newPrice: 174,
    volume: "12 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/2023/PEACH_12ml-500x600-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-peach_-12ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9702",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Latte, 7 мл",
    oldPrice: 159,
    newPrice: 111,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Lint_base/LATTE_(01)-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-latte_-7ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9701",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Latte, 35 мл",
    oldPrice: 460,
    newPrice: 322,
    volume: "35 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/2023/LATTE_35ml-500x600-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-latte_-35ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9700",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Latte, 12 мл",
    oldPrice: 249,
    newPrice: 174,
    volume: "12 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/2023/LATTE_12ml-500x600-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-latte_-12ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9699",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Delicate Rose, 7 мл",
    oldPrice: 159,
    newPrice: 111,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/camuflage%20gel/Lint%20Base/New%20color_Lint_Base_Delicate_Rose_7_ml-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-delicate-rose_-7ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9698",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Delicate Rose, 35 мл",
    oldPrice: 460,
    newPrice: 322,
    volume: "35 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/camuflage%20gel/Lint%20Base/New%20color_Lint%20base%20Delicate%20Rose,%2035%20ml-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-delicate-rose_-35ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9697",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Delicate Rose, 12 мл",
    oldPrice: 249,
    newPrice: 174,
    volume: "12 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/camuflage%20gel/Lint%20Base/New%20color_Lint%20base%20Delicate%20Rose,%2012%20ml-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-delicate-rose_-12ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9696",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Cold Rose, 7 мл",
    oldPrice: 159,
    newPrice: 111,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Lint_base/COLD_ROSE_(01)-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-cold-rose_-7ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9695",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Cold Rose, 35 мл",
    oldPrice: 460,
    newPrice: 322,
    volume: "35 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/2023/COLDROSE_35ml-500x600-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-cold-rose_-35ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9694",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Lint base gel Cold Rose, 12 мл",
    oldPrice: 249,
    newPrice: 174,
    volume: "12 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/2023/COLDROSE_12ml-500x600-306x390.png",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/lint-base/bazove-pokrittya-dlya-gelj_laku-lint-base-gel-cold-rose_-12ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9305",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 03, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Color_base/7%20ml/03_CB-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche_bazove_pokrittya_cover_base_gel_03__7ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9222",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 04, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Color_base/7%20ml/04_CB-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche_bazove_pokrittya_cover_base_gel_04__7ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9164",
    title: "Гель-лак",
    subtitle: "Гель-лак French White, 7 мл",
    oldPrice: 180,
    newPrice: 90,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/category/nail_aesthetic/gel%20baza/gel_baza_20091835-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/gelj_lak_french_white_7_ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9120",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 02, 7 мл",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image: "",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche_bazove_pokrittya_02__7ml/",
    rating: 0,
    reviews: 0,
  },
  {
    id: "9119",
    title: "Камуфлююче базове покриття",
    subtitle: "Камуфлююче базове покриття Cover Base Gel 01, 7 мл ",
    oldPrice: 185,
    newPrice: 130,
    volume: "7 мл",
    image:
      "https://kodi-professional.ua/image/cache/catalog/data/novyy/new_01/Color_base/7%20ml/01_CB-306x390.jpg",
    href: "https://kodi-professional.ua/uk/baza-i-top-dlya-gel-laka/bazatop-dlya-gel-lakuquot-french-quot/cover-base/kamuflyuyuche_bazove_pokrittya_01__7ml/",
    rating: 0,
    reviews: 0,
  },
];

export default camouflageBasesKodi;
