// lib/kodiCollections.js

export const kodiNailsCollections = [
  { id: "5d-moon-light", name: "5D Moon Light", count: 6, route: "#" },
  { id: "animal-print", name: "Animal Print", count: 10, route: "#" },
  { id: "art-sprinkle", name: "Art Sprinkle", count: 31, route: "#" },
  {
    id: "basic-aquamarine",
    name: "Basic Collection AQUAMARINE (AQ)",
    count: 19,
    route: "#",
  },
  {
    id: "basic-black-white",
    name: "Basic Collection BLACK&WHITE (BW)",
    count: 24,
    route: "#",
  },
  {
    id: "basic-blue",
    name: "Basic Collection BLUE (B)",
    count: 46,
    route: "#",
  },
  {
    id: "basic-bright",
    name: "Basic Collection BRIGHT (BR)",
    count: 55,
    route: "#",
  },
  {
    id: "basic-cappuccino",
    name: "Basic Collection CAPPUCCINO (CN)",
    count: 14,
    route: "#",
  },
  {
    id: "basic-cappuccino-2",
    name: "Basic Collection Cappucino (CN)",
    count: 2,
    route: "#",
  },
  {
    id: "basic-green-yellow",
    name: "Basic Collection GREEN&YELLOW (GY)",
    count: 16,
    route: "#",
  },
  {
    id: "basic-lilac",
    name: "Basic Collection LILAC (LC)",
    count: 28,
    route: "#",
  },
  {
    id: "basic-milk",
    name: "Basic Collection MILK (M)",
    count: 17,
    route: "#",
  },
  {
    id: "basic-pink",
    name: "Basic Collection PINK (P)",
    count: 21,
    route: "#",
  },
  { id: "basic-red", name: "Basic Collection RED (R)", count: 9, route: "#" },
  {
    id: "basic-salmon",
    name: "Basic Collection SALMON (SL)",
    count: 26,
    route: "#",
  },
  {
    id: "basic-shine",
    name: "Basic Collection SHINE (SH)",
    count: 60,
    route: "#",
  },
  {
    id: "basic-violet",
    name: "Basic Collection VIOLET (V)",
    count: 25,
    route: "#",
  },
  {
    id: "basic-wine",
    name: "Basic Collection WINE (WN)",
    count: 9,
    route: "#",
  },
  { id: "cat-shine", name: "Cat Shine", count: 39, route: "#" },
  { id: "cherry-cat-eye", name: "Cherry Cat Eye", count: 5, route: "#" },
  { id: "coffee-paradise", name: "Coffee Paradise", count: 23, route: "#" },
  { id: "contrast-mood", name: "Contrast Mood", count: 5, route: "#" },
  { id: "diamond-sky", name: "Diamond Sky", count: 28, route: "#" },
  { id: "dress-code", name: "Dress Code", count: 6, route: "#" },
  { id: "eclipse", name: "Eclipse", count: 6, route: "#" },
  { id: "ethno-fashion", name: "Ethno Fashion", count: 10, route: "#" },
  { id: "fashion-look", name: "Fashion Look", count: 5, route: "#" },
  { id: "galaxy-glow-cat", name: "Galaxy Glow Cat", count: 6, route: "#" },
  { id: "glam-gloss", name: "Glam Gloss", count: 8, route: "#" },
  { id: "golden-brown", name: "Golden Brown", count: 10, route: "#" },
  { id: "jungle", name: "Jungle", count: 12, route: "#" },
  { id: "milk-7ml", name: "Milk (M), 7 мл", count: 1, route: "#" },
  { id: "moon-light", name: "Moon light", count: 147, route: "#" },
  { id: "mouline", name: "Mouline", count: 5, route: "#" },
  { id: "natural-motives", name: "Natural Motives", count: 30, route: "#" },
  { id: "night-glow", name: "Night Glow", count: 12, route: "#" },
  { id: "perfect-match", name: "Perfect Match", count: 9, route: "#" },
  { id: "pink-silk", name: "Pink silk", count: 4, route: "#" },
  { id: "polar-light", name: "Polar Light", count: 12, route: "#" },
  { id: "porcelain", name: "Porcelain Collection", count: 7, route: "#" },
  { id: "rainbow-flakes", name: "Rainbow Flakes", count: 6, route: "#" },
  { id: "rich-stone", name: "Rich Stone", count: 14, route: "#" },
  { id: "romantic-nude", name: "Romantic Nude", count: 11, route: "#" },
  { id: "royal-temptation", name: "Royal Temptation", count: 7, route: "#" },
  { id: "sparkle", name: "Sparkle", count: 2, route: "#" },
  { id: "tornado", name: "Tornado", count: 6, route: "#" },
  { id: "wedding-style", name: "Wedding Style", count: 7, route: "#" },
  {
    id: "natural-motives-7ml",
    name: "Гель-лак 'Natural Motives', 7 мл",
    count: 1,
    route: "#",
  },
  {
    id: "cat-shine-7ml",
    name: "Гель-лак Cat Shine, 7 мл",
    count: 1,
    route: "#",
  },
];

export default kodiNailsCollections;
